import Head from 'next/head'
import react from "react"
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai"
import Image from "next/image";
import githubProfile from "../public/githubProfile.jpg"
import design from "../public/undraw_Design_thinking_re_644h.png"
import code from "../public/undraw_code_inspection_bdl7.png"
import service from "../public/undraw_Services_re_hu5n.png"


export default function Home() {
  return (
    <div>
      <Head>
        <title>BjoPortfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 ">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-xl">bjo-droid</h1>
            <ul className=" flex items-center">
              <li><BsFillMoonStarsFill className=" cursor-pointer text-2xl"/></li>
              <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">PlaceHolder</a></li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium">John Doe</h2>
            <h3 className=" text-2xl py-2">Title</h3>
            <p className=" text-md py-5 leading-8 text-gray-800">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur incidunt provident ipsa minus officia maiores, nihil facilis accusantium! Asperiores aliquid unde commodi iure dicta minus obcaecati cumque quis porro quia suscipit in libero, consectetur iusto magni temporibus. Hic quidem cupiditate tempora inventore esse quibusdam unde necessitatibus nobis quo quaerat! Laboriosam.</p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className=" relative mt-20 ">
            <Image src={githubProfile} className=" mx-auto rounded-full w-80 h-80" />
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-3xl py-1">Services</h3>
            <p className="text-md py-2 leading-8 text-gray-800">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea odio laborum deserunt maiores quae nisi possimus aspernatur eaque dignissimos sit praesentium in, necessitatibus, dolor nostrum rem animi inventore commodi cum consequatur doloremque quo enim neque. Perspiciatis ipsum perferendis tempore est unde. Ratione placeat similique cupiditate incidunt est officiis nam fugit.</p>
            <p className="text-md py-2 leading-8 text-gray-800">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea odio laborum deserunt maiores quae nisi possimus aspernatur eaque dignissimos sit praesentium in, necessitatibus, dolor nostrum rem animi inventore commodi cum consequatur doloremque quo enim neque. Perspiciatis ipsum perferendis tempore est unde. Ratione placeat similique cupiditate incidunt est officiis nam fugit.</p>
          </div>
          <div>
            <div className=" text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={design} width={100} height={100}/>
              <h3 className=" text-lg font-medium pt-8 pb-2">Designs</h3>
              <p className=" py-2">Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse optio in voluptas nobis quisquam aliquid quaerat ad labore quia iste!</p>
              <h4 className=" py-4 text-teal-600">Design Tools</h4>
              <p className=" text-gray-800 py-1">Tool</p>
              <p className=" text-gray-800 py-1">Tool</p>
              <p className=" text-gray-800 py-1">Tool</p>
              <p className=" text-gray-800 py-1">Tool</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
