import Head from 'next/head'
import react from "react"
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from "react-icons/ai"
import Image from "next/image";
import githubProfile from "../public/githubProfile.jpg"
import design from "../public/undraw_Design_thinking_re_644h.png"
import code from "../public/undraw_code_inspection_bdl7.png"
import service from "../public/undraw_Services_re_hu5n.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import { useState } from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>BJO Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between dark:text-white">
            <h1 className=" text-xl">bjo-droid</h1>
            <ul className=" flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className=" cursor-pointer text-2xl"/></li>
              <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">PlaceHolder</a></li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className=" text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">bjo-droid</h2>
            <h3 className=" text-2xl py-2 dark:text-white md:text-3xl" >Title</h3>
            <p className=" text-md py-5 leading-8 text-gray-800 dark:text-gray-200 md:text-xl max-w-xl mx-auto">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur incidunt provident ipsa minus officia maiores, nihil facilis accusantium! Asperiores aliquid unde commodi iure dicta minus obcaecati cumque quis porro quia suscipit in libero, consectetur iusto magni temporibus. Hic quidem cupiditate tempora inventore esse quibusdam unde necessitatibus nobis quo quaerat! Laboriosam.</p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className=" relative mt-20 ">
            <Image src={githubProfile} className=" mx-auto rounded-full w-80 h-80 mt-20  md:w-96 md:h-96" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugit enim, fugiat eum impedit sunt repellat molestiae. Repellat, quisquam suscipit optio laboriosam assumenda veniam quos rerum minima illo quas. Voluptas sint quaerat dolor voluptatem exercitationem asperiores quo, reprehenderit ab rem aut magni ea explicabo possimus? Sequi fugiat eos quidem officiis tempora.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, voluptatum!</p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className=" mx-auto" src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni, exercitationem.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image className=" mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Lorem ipsum dolor sit amet.
              </h3>
              <p className="py-2">Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit, at.</p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
                <Image className=" mx-auto" src={service} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">Lorem ipsum dolor sit amet consectetur adipisicing elit. At, voluptatibus.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque minus similique minima iusto perspiciatis. Nobis unde aliquam tenetur inventore natus praesentium quo at accusantium quibusdam asperiores ipsa eveniet eius, in tempora, rerum accusamus commodi aliquid ratione fuga ut impedit repudiandae fugit ipsum repellendus? Ex deleniti provident laboriosam obcaecati ducimus ipsa.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum, natus.</p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
